name: fun_meet
description: "A new Flutter project. Rencontre fun"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # Firebase Dependencies (versions rétrogradées pour compatibilité)
  firebase_core: ^2.15.1
  firebase_auth: ^4.7.3
  cloud_firestore: ^4.8.5
  firebase_storage: ^11.2.6

  # State Management
  provider: ^6.1.1

  # Form Validation
  form_field_validator: ^1.1.0

  # Image Picker
  image_picker: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
